### PR TITLE
MinGW without conan package tools

### PR DESCRIPTION
**Pull request by tim-lebedkov**

### CODE REVIEW

**Comment by tim-lebedkov** [comment]
The build failure on Travis seems to be unrelated to my changes.

**Comment by lasote** [comment]
Great job! Let me study it and see if I can integrate something in pacakge tools to simplify the appveyor script.
Just a question, in the issue #4 you mention that you are using a compiler called "GCC 4.9", it's "GCC 4.9 with SEH exception handling and Posix threads". 
I don't know much about mingw, If I try to link with your zlib package (compiled with that mingw) with a different mingw(maybe without posix support) should work? I'm trying to know if we should support in conan more sub-settings for gcc (mingw) or it's ok.
The key is: If the settings change, the package have to change, if the settings don't change, the packages have to be compatible each other. What do you think? Should we study to introduce new compilers settings?

Thank you very much for your work!

**Comment by tim-lebedkov** [comment]
See my comment for explanations: https://github.com/conan-io/conan/issues/364#issuecomment-231600148

**Comment by lasote** [comment]
We want to release the conan 0.11 version first, then I need to update this repository with the Mingw builds for appveyor. Sorry, It should be quick, this week.

**Comment by lasote** [comment]
Hi! you have mingw 4.9 packages available in conan.io.
Please, download the new 0.11 conan version and remember, now there are three new settings for gcc compiler: 

    libcxx: [libstdc++, libstdc++11]
    threads: [None, posix, win32] #  Windows MinGW
    exception: [None, dwarf2, sjlj, seh] # Windows MinGW
You will need to add them (with a default value) to your ~/.conan/conan.conf or pass with -s argument to conan install.

I hope it works for you, if don't just write me, tomorrow I can help you with any issue.
Thank you very very much for your help, without this PR I wouldn't be able to add this feature to conan.

**Comment by tim-lebedkov** [comment]
Great, thank you!

**Pull request closed without merging**
